### PR TITLE
Add `sentry-ruby` integration

### PR DESCRIPTION
**Pull request by rewritten**
### Description of changes

Added support for `sentry-ruby` gem.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rewritten** [comment]
cc: @n-gubernator and @zhukovpe

**Comment by reidmorrison** [comment]
Is there any need to keep the old sentry-raven approach around any more? 
If anyone upgrades semantic logger after this switch, they could switch to the new `sentry-ruby` gem?

**Comment by rewritten** [comment]
I have been part of plenty of projects that are tied for one reason or another to older versions of one or another library. Specifically, one project may already be using `sentry-raven` with both explicit calls and as a semantic logger backend. 

Given that it is not an issue to support both sentry-raven and sentry-ruby, I would prefer to allow those projects to upgrade their sentry integration when they can, but at the same time keep semantic logger up to date and benefit from other new features and fixes.

I would definitely hard-deprecate this in a near future, but it’s a breaking change and right now there is no need to break.

**Comment by rewritten** [comment]
Hey @reidmorrison, did my previous comment come off as pedantic or something? I apologize if that is the case.

If you need me to change the code in any way (including removing sentry-raven support) please tell me so I can adapt the PR.

**Comment by reidmorrison** [comment]
@rewritten sorry, I just have not had time to respond. No issue at all. With Semantic Logger v5 we could remove the old one.

Thank you for taking the time to add this new feature, much appreciated. :tada:

**Pull request merged**
