### PR TITLE
Hang Due to Async#submit_request Not Waiting for Child Thread to Join

### PR DESCRIPTION
**Pull request by eviljoel**
When closing the async processor, the `Async#submit_request` method can return before the child thread has finished executing. This can cause the program to hang if the child thread dies in the middle of a second call to `Async#submit_request`. The solution is to wait for the child thread to 'join' before returning.

I can reproduce the issue with the following program. Note that you might need to wait several hours for a hang to occur. (Due to thread scheduler differences, I've had the most luck on CentOS 7 and Ubuntu 20.04.) I've included code to get the stack trace so you can see that the program is locked on the expected line:
```
require 'semantic_logger'
require 'stringio'

puts "Run 'kill -SIGUSR1 #{$$}' to get a stack trace once the program hangs."
Signal.trap('USR1') do
  STDERR.puts('Thread Dump')
  Thread.list.each do |thread|
    STDERR.puts
    STDERR.puts(thread.backtrace.join("\n"))
  end
end

# This helps encourage the thread scheduler to switch threads more often. It isn't strictly required
#   for the error to occur, but helps it to occur faster.
2.times do
  Thread.new do
    counter = 0
    while true
      counter = counter + 1
    end    
  end
end

while true
  SemanticLogger.clear_appenders!
  SemanticLogger.add_appender(appender: SemanticLogger::Appender::IO.new(StringIO.new))
  # When the time stops incrementing for a few seconds, the program has hung.
  puts "Current Time : " + Time.new.inspect
end
```
The program hangs on this line:
https://github.com/reidmorrison/semantic_logger/blob/6a7be665a8c6eaf5b9441d8aabc16ec47b3b0231/lib/semantic_logger/appender/async.rb#L205

### Issue # (if available)

* [234](https://github.com/reidmorrison/semantic_logger/issues/234) (My work colleague filed this issue, so I know this is related.)

### Changelog

```
- Fixed a thread safety issue in Async#submit_request. When closing the async
  processor, the submit_request method could return before the child thread had
  finished executing. This caused the program to hang if the child thread
  dies in the middle of a second call to Async#submit_request. The solution was
  to wait for the child thread to 'join' before returning.
```

### Description of changes

* Don't set `@thread` to nil when the thread is stopped. (No behavior seems to depend on that.)
* `join` the child thread before returning from `submit_request` when processing the 'close' command.
* AsyncBatch now listens to :close message.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by reidmorrison** [comment]
Looks like tests are hanging with this change 🤔

**Comment by reidmorrison** [comment]
Suggest merging master to get the passing Ruby versions

**Comment by eviljoel** [comment]
@reidmorrison, please give it a try now.

**Comment by eviljoel** [comment]
@reidmorrison, there is a TODO with the text: `# TODO: Prevent new close requests once this appender has been closed.` I'm not sure if you consider this change as having resolved this TODO or not. Let me know if you want me to remove it.

**Comment by keithrbennett** [comment]
Excellent find and solution, @eviljoel . In the test suite failure that spawned this research (issue at https://github.com/reidmorrison/semantic_logger/issues/234), I was indeed clearing and adding appenders in quick succession (for each RSpec test example). If I understand correctly, it's good news that for the most common use cases, where appenders are added at the beginning of the application and then not changed, this bug should not have affected production use.

@reidmorrison Could you include this change in your upcoming release?

**Comment by keithrbennett** [comment]
Building on @eviljoel's identification of the problem, I looked into this further. The error occurs when the close is called subsequent times on the same appender; each appender has its own thread, so if the problem is per thread then it's also per appender.

Given that, I think it may be enough to guard the appender instance's close method against multiple calls (as Reid suggested in his TODO). If we modify the close method like this, for example:

```ruby
      # Close all appenders and flush any outstanding messages.
      def close
        if @close_already_requested
          # warn "Close already requested on thread #{Thread.current}."
          return
        end
        @close_already_requested = true
        submit_request(:close)
      end
```

...then I think the problem will not occur. I still need to test this but wanted to post this before a solution to this problem is adopted.

This solution would eliminate the need for the calling thread to wait for the close to complete. Waiting would be problematic if, for example, the appender's close implementation was doing time consuming network calls, or if the closes were happening at an extremely high frequency.

**Comment by keithrbennett** [comment]
The script has now been running for over 2 hours and 20 minutes without error. I am fairly confident this fix solves the problem.

**Comment by eviljoel** [comment]
@keithrbennett, your solution is not complete. You need something to set `@close_already_requested` back to `false`. Even then, I'm pretty sure you can only set it safely back to 'false' if you use a mutex or you will have a similar problem (although it might occur less frequently).

**Comment by keithrbennett** [comment]
@eviljoel Is this what you had in mind?: https://github.com/reidmorrison/semantic_logger/pull/238

**Comment by eviljoel** [comment]
@keithrbennett, I thought about this a bit more. I'm pretty sure you can't implement this correctly without `join`, at least not in an efficient manner.

There are several problems with your proposed solution in PR [238](https://github.com/reidmorrison/semantic_logger/pull/238). I'll comment on it there.

**Comment by reidmorrison** [comment]
To help with this process, I completely refactored the way Async and BatchAsync are handled. This should make it much easier to locate the methods that would need semaphore protection: https://github.com/reidmorrison/semantic_logger/pull/242

Also added documentation on how to test whether application code is logging correctly. See the section "Writing Tests" at the end of the guide: https://logger.rocketjob.io/api.html

We can include these changes as part of a new major release of Semantic Logger, that will also raise the minimum ruby version to 2.7.

**Comment by reidmorrison** [comment]
@eviljoel can you try this branch and let me know how it goes for you?

Inside Gemfile:
`gem "semantic_logger", github: "reidmorrison/semantic_logger", branch: "feature/refactor-async"`

**Comment by reidmorrison** [comment]
I am abandoning the changes in the refactor branch since they could break existing users of Semantic Logger and that is not a risk worth taking.
I would suggest using a simpler logging implementation like the built in Ruby Logger to meet your unique use case.

**Pull request closed without merging**
